name       : libnvme
version    : '1.0'
release    : 1
source     :
    - https://github.com/linux-nvme/libnvme/archive/refs/tags/v1.0.tar.gz : 387524b1c24a4091a88bfb258c98c054f716da210e77702f0709164740370807
license    : LGPL-2.1-or-later
component  : programming.library
summary    : C Library for NVM Express
description: |
    libnvme provides type definitions for NVMe specification structures, enumerations, and bit fields, helper functions to construct, dispatch, and decode commands and payloads, and utilities to connect, scan, and manage nvme devices.
builddeps  :
    - pkgconfig(json-c)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
